### ISSUE TITLE
NoSuchMethodError: com.google.api.client.http.HttpHeaders.getAuthenticateAsList

### ISSUE THREAD

**Issue by erikdubbelboer** [google/google-oauth-java-client#115]
I'm getting the following error when trying to upload a blob to Google Cloud Storage. As you can see the error originates from the oauth `Credential.handleResponse` but I'm not sure if the bug is not in the [api client](https://github.com/google/google-http-java-client) and should be filed there?

The location of the error seems to be [Credential.java#L245](https://github.com/google/google-oauth-java-client/blob/c7815388b75de6a55a149a6cc64cc9cc37894787/google-oauth-client/src/main/java/com/google/api/client/auth/oauth2/Credential.java#L245)
```
java.lang.NoSuchMethodError: com.google.api.client.http.HttpHeaders.getAuthenticateAsList()Ljava/util/List;
        at com.google.api.client.auth.oauth2.Credential.handleResponse(Credential.java:245) ~[?:?]
        at com.google.api.client.googleapis.media.MediaUploadErrorHandler.handleResponse(MediaUploadErrorHandler.java:78) ~[?:?]
        at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:992) ~[google-http-client-1.15.0-rc.jar:?]
        at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequestWithoutGZip(MediaHttpUploader.java:545) ~[?:?]
        at com.google.api.client.googleapis.media.MediaHttpUploader.resumableUpload(MediaHttpUploader.java:417) ~[?:?]
        at com.google.api.client.googleapis.media.MediaHttpUploader.upload(MediaHttpUploader.java:336) ~[?:?]
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:427) ~[?:?]
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352) ~[?:?]
        at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469) ~[?:?]
        at io.druid.storage.google.GoogleDataSegmentPusher.insert(GoogleDataSegmentPusher.java:93) ~[?:?]
        at io.druid.storage.google.GoogleDataSegmentPusher.uploadDataSegment(GoogleDataSegmentPusher.java:109) ~[?:?]
        at io.druid.storage.google.GoogleDataSegmentPusher.push(GoogleDataSegmentPusher.java:141) ~[?:?]
        at io.druid.indexing.common.task.IndexTask$1.push(IndexTask.java:343) ~[druid-indexing-service-0.8.4-SNAPSHOT.jar:0.8.4-SNAPSHOT]
        at io.druid.indexing.common.index.YeOldePlumberSchool$1.finishJob(YeOldePlumberSchool.java:179) ~[druid-indexing-service-0.8.4-SNAPSHOT.jar:0.8.4-SNAPSHOT]
        at io.druid.indexing.common.task.IndexTask.generateSegment(IndexTask.java:399) ~[druid-indexing-service-0.8.4-SNAPSHOT.jar:0.8.4-SNAPSHOT]
        at io.druid.indexing.common.task.IndexTask.run(IndexTask.java:213) ~[druid-indexing-service-0.8.4-SNAPSHOT.jar:0.8.4-SNAPSHOT]
        at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:285) [druid-indexing-service-0.8.4-SNAPSHOT.jar:0.8.4-SNAPSHOT]
        at io.druid.indexing.overlord.ThreadPoolTaskRunner$ThreadPoolTaskRunnerCallable.call(ThreadPoolTaskRunner.java:265) [druid-indexing-service-0.8.4-SNAPSHOT.jar:0.8.4-SNAPSHOT]
        at java.util.concurrent.FutureTask.run(FutureTask.java:262) [?:1.7.0_91]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [?:1.7.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [?:1.7.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.7.0_91]
```

The code for the `GoogleDataSegmentPusher` in the stack trace can be found here: [GoogleDataSegmentPusher.java#L83-L93](https://github.com/erikdubbelboer/druid/blob/google-0.8.4/extensions/google-extensions/src/main/java/io/druid/storage/google/GoogleDataSegmentPusher.java#L83-L93)

The code to create the `Storage` client can be found here: [GoogleStorageDruidModule.java#L108-L115](https://github.com/erikdubbelboer/druid/blob/google-0.8.4/extensions/google-extensions/src/main/java/io/druid/storage/google/GoogleStorageDruidModule.java#L108-L115)

Before the `insert` the `Storage` object is used to `get` one file which works perfectly fine, so it has nothing to do with access rights etc.

As you can see in my [pom.xml](https://github.com/erikdubbelboer/druid/blob/google-0.8.4/extensions/google-extensions/pom.xml#L43-L52), I'm using `google-api-services-storage` and `google-http-client-jackson` (not jackson2 because that gives me `java.lang.NoSuchMethodError: com.google.api.client.json.jackson2.JacksonFactory.getDefaultInstance`. `new JacksonFactory()` works with jackson2 though but doesn't fix this issue).

**Comment by erikdubbelboer** [comment]
I found out that some other library depended on version 1.15 of `google-http-client`. I'm new to Maven so I have no idea why it decided to include 1.15 and ignore my dependency on 1.21. Updating the other library to a new version has fixed my problem.

**Comment by KetanPote** [comment]
Please add this dependency to your POM.xml

		<dependency>
		  <groupId>com.google.api-client</groupId>
		  <artifactId>google-api-client</artifactId>
		  <version>1.23.0</version>
		</dependency>

I stuck in same, It fixed my issue.

**Comment by phd147** [comment]
> Please add this dependency to your POM.xml
> 
> ```
> 	<dependency>
> 	  <groupId>com.google.api-client</groupId>
> 	  <artifactId>google-api-client</artifactId>
> 	  <version>1.23.0</version>
> 	</dependency>
> ```
> 
> I stuck in same, It fixed my issue.



> Please add this dependency to your POM.xml
> 
> ```
> 	<dependency>
> 	  <groupId>com.google.api-client</groupId>
> 	  <artifactId>google-api-client</artifactId>
> 	  <version>1.23.0</version>
> 	</dependency>
> ```
> 
> I stuck in same, It fixed my issue.

thanks a lot, I found my problem
