### ISSUE TITLE
Double encryption when user isn't already logged in.

### ISSUE THREAD

**Issue by ncrimmel** [google/google-oauth-java-client#148]
If a user is logged in, authorization goes through fine. If a user is not logged in, we receive the following error.

Caused by: com.google.api.client.auth.oauth2.TokenResponseException: 400 Bad Request
{
  "error" : "invalid_grant"
}
        at com.google.api.client.auth.oauth2.TokenResponseException.from(TokenResponseException.java:105)
        at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:287)
        at com.google.api.client.googleapis.auth.oauth2.GoogleAuthorizationCodeTokenRequest.execute(GoogleAuthorizationCodeTokenRequest.java:158)

**Comment by mattwhisenhunt** [comment]
@ncrimmel is this a bug report or a question about how to use the library?

If it is the former I am going to need to more information to be able to reproduce your result. Do you have a minimal bit of code that you could post that is causing this error?

**Comment by mattwhisenhunt** [comment]
Thank you for filing this issue. We asked some clarifying questions a week or more ago and never heard back from you. We are unable to proceed with this issue until then, so we are closing it. Please feel free to re-open this issue with more information.
