### ISSUE TITLE
 This library should compile with JDK9

### ISSUE THREAD

**Issue by jadekler** [google/google-oauth-java-client#202]
But, it does not. When I use JDK8, `mvn install` works. When I use JDK9, `mvn install` fails. Here is the failure from `mvn install` with JDK9:

```
Exception during population of metadata for com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow
DataNucleus Enhancer completed with an error. Please review the enhancer log for full details. Some classes may have been enhanced but some caused errors

[ERROR] --------------------
[ERROR]  Standard error from the DataNucleus tool + org.datanucleus.enhancer.DataNucleusEnhancer :
[ERROR] --------------------
[ERROR] Aug 07, 2018 1:45:32 PM org.datanucleus.enhancer.DataNucleusEnhancer <init>
INFO: DataNucleus Enhancer : Using ClassEnhancer "ASM" for API "JDO"
Aug 07, 2018 1:45:32 PM org.datanucleus.enhancer.DataNucleusEnhancer main
INFO: DataNucleus Enhancer (version 2.1.3) : Enhancement of classes
Aug 07, 2018 1:45:32 PM org.datanucleus.metadata.MetaDataManager loadClasses
SEVERE: Class "com.google.api.client.extensions.servlet.auth.AbstractCallbackServlet" was not found in the CLASSPATH. Please check your specification and your CLASSPATH.
org.datanucleus.exceptions.ClassNotResolvedException: Class "com.google.api.client.extensions.servlet.auth.AbstractCallbackServlet" was not found in the CLASSPATH. Please check your specification and your CLASSPATH.
	at org.datanucleus.JDOClassLoaderResolver.classForName(JDOClassLoaderResolver.java:247)
	at org.datanucleus.JDOClassLoaderResolver.classForName(JDOClassLoaderResolver.java:412)
	at org.datanucleus.metadata.MetaDataManager.loadClasses(MetaDataManager.java:436)
	at org.datanucleus.enhancer.DataNucleusEnhancer.getFileMetadataForInput(DataNucleusEnhancer.java:791)
	at org.datanucleus.enhancer.DataNucleusEnhancer.enhance(DataNucleusEnhancer.java:582)
	at org.datanucleus.enhancer.DataNucleusEnhancer.main(DataNucleusEnhancer.java:1316)

Aug 07, 2018 1:45:32 PM org.datanucleus.metadata.MetaDataManager loadClasses
SEVERE: Class "com.google.api.client.extensions.servlet.auth.oauth2.AbstractAuthorizationCodeServlet" was not found in the CLASSPATH. Please check your specification and your CLASSPATH.
org.datanucleus.exceptions.ClassNotResolvedException: Class "com.google.api.client.extensions.servlet.auth.oauth2.AbstractAuthorizationCodeServlet" was not found in the CLASSPATH. Please check your specification and your CLASSPATH.
	at org.datanucleus.JDOClassLoaderResolver.classForName(JDOClassLoaderResolver.java:247)
	at org.datanucleus.JDOClassLoaderResolver.classForName(JDOClassLoaderResolver.java:412)
	at org.datanucleus.metadata.MetaDataManager.loadClasses(MetaDataManager.java:436)
	at org.datanucleus.enhancer.DataNucleusEnhancer.getFileMetadataForInput(DataNucleusEnhancer.java:791)
	at org.datanucleus.enhancer.DataNucleusEnhancer.enhance(DataNucleusEnhancer.java:582)
	at org.datanucleus.enhancer.DataNucleusEnhancer.main(DataNucleusEnhancer.java:1316)

Aug 07, 2018 1:45:32 PM org.datanucleus.metadata.MetaDataManager loadClasses
SEVERE: Class "com.google.api.client.extensions.servlet.auth.oauth2.AbstractAuthorizationCodeCallbackServlet" was not found in the CLASSPATH. Please check your specification and your CLASSPATH.
org.datanucleus.exceptions.ClassNotResolvedException: Class "com.google.api.client.extensions.servlet.auth.oauth2.AbstractAuthorizationCodeCallbackServlet" was not found in the CLASSPATH. Please check your specification and your CLASSPATH.
	at org.datanucleus.JDOClassLoaderResolver.classForName(JDOClassLoaderResolver.java:247)
	at org.datanucleus.JDOClassLoaderResolver.classForName(JDOClassLoaderResolver.java:412)
	at org.datanucleus.metadata.MetaDataManager.loadClasses(MetaDataManager.java:436)
	at org.datanucleus.enhancer.DataNucleusEnhancer.getFileMetadataForInput(DataNucleusEnhancer.java:791)
	at org.datanucleus.enhancer.DataNucleusEnhancer.enhance(DataNucleusEnhancer.java:582)
	at org.datanucleus.enhancer.DataNucleusEnhancer.main(DataNucleusEnhancer.java:1316)

Aug 07, 2018 1:45:32 PM org.datanucleus.metadata.MetaDataManager loadClasses
INFO: Class "com.google.api.client.extensions.servlet.auth.package-info" has no MetaData or annotations.
Aug 07, 2018 1:45:32 PM org.datanucleus.metadata.MetaDataManager loadClasses
SEVERE: Class "com.google.api.client.extensions.servlet.auth.AbstractFlowUserServlet" was not found in the CLASSPATH. Please check your specification and your CLASSPATH.
org.datanucleus.exceptions.ClassNotResolvedException: Class "com.google.api.client.extensions.servlet.auth.AbstractFlowUserServlet" was not found in the CLASSPATH. Please check your specification and your CLASSPATH.
	at org.datanucleus.JDOClassLoaderResolver.classForName(JDOClassLoaderResolver.java:247)
	at org.datanucleus.JDOClassLoaderResolver.classForName(JDOClassLoaderResolver.java:412)
	at org.datanucleus.metadata.MetaDataManager.loadClasses(MetaDataManager.java:436)
	at org.datanucleus.enhancer.DataNucleusEnhancer.getFileMetadataForInput(DataNucleusEnhancer.java:791)
	at org.datanucleus.enhancer.DataNucleusEnhancer.enhance(DataNucleusEnhancer.java:582)
	at org.datanucleus.enhancer.DataNucleusEnhancer.main(DataNucleusEnhancer.java:1316)

Aug 07, 2018 1:45:33 PM org.datanucleus.jdo.metadata.JDOAnnotationReader processClassAnnotations
INFO: Class "com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow" has been specified with JDO annotations so using those.
Aug 07, 2018 1:45:33 PM org.datanucleus.metadata.MetaDataManager loadClasses
INFO: Class "com.google.api.client.extensions.auth.helpers.oauth.package-info" has no MetaData or annotations.
Aug 07, 2018 1:45:33 PM org.datanucleus.jdo.metadata.JDOAnnotationReader processClassAnnotations
INFO: Class "com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacCredential" has been specified with JDO annotations so using those.
Aug 07, 2018 1:45:33 PM org.datanucleus.metadata.MetaDataManager loadClasses
INFO: Class "com.google.api.client.extensions.auth.helpers.ThreeLeggedFlow" has no MetaData or annotations.
Aug 07, 2018 1:45:33 PM org.datanucleus.metadata.MetaDataManager loadClasses
INFO: Class "com.google.api.client.extensions.auth.helpers.package-info" has no MetaData or annotations.
Aug 07, 2018 1:45:33 PM org.datanucleus.metadata.MetaDataManager loadClasses
INFO: Class "com.google.api.client.extensions.auth.helpers.Credential" has no MetaData or annotations.
Aug 07, 2018 1:45:33 PM org.datanucleus.enhancer.DataNucleusEnhancer main
SEVERE: DataNucleus Enhancer completed with an error. Please review the enhancer log for full details. Some classes may have been enhanced but some caused errors
Exception during population of metadata for com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow
org.datanucleus.exceptions.NucleusUserException: Exception during population of metadata for com.google.api.client.extensions.auth.helpers.oauth.OAuthHmacThreeLeggedFlow
	at org.datanucleus.metadata.MetaDataManager$1.run(MetaDataManager.java:2402)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.datanucleus.metadata.MetaDataManager.populateAbstractClassMetaData(MetaDataManager.java:2387)
	at org.datanucleus.metadata.MetaDataManager.populateFileMetaData(MetaDataManager.java:2224)
	at org.datanucleus.metadata.MetaDataManager.initialiseFileMetaDataForUse(MetaDataManager.java:924)
	at org.datanucleus.metadata.MetaDataManager.loadClasses(MetaDataManager.java:489)
	at org.datanucleus.enhancer.DataNucleusEnhancer.getFileMetadataForInput(DataNucleusEnhancer.java:791)
	at org.datanucleus.enhancer.DataNucleusEnhancer.enhance(DataNucleusEnhancer.java:582)
	at org.datanucleus.enhancer.DataNucleusEnhancer.main(DataNucleusEnhancer.java:1316)
Caused by: java.lang.NullPointerException
	at java.base/java.util.Arrays.binarySearch(Arrays.java:2381)
	at org.datanucleus.store.types.TypeManager.isDefaultEmbeddedType(TypeManager.java:228)
	at org.datanucleus.metadata.AbstractMemberMetaData.populate(AbstractMemberMetaData.java:489)
	at org.datanucleus.metadata.ClassMetaData.populateMemberMetaData(ClassMetaData.java:543)
	at org.datanucleus.metadata.ClassMetaData.populate(ClassMetaData.java:205)
	at org.datanucleus.metadata.MetaDataManager$1.run(MetaDataManager.java:2393)
	... 8 more
Nested Throwables StackTrace:
java.lang.NullPointerException
	at java.base/java.util.Arrays.binarySearch(Arrays.java:2381)
	at org.datanucleus.store.types.TypeManager.isDefaultEmbeddedType(TypeManager.java:228)
	at org.datanucleus.metadata.AbstractMemberMetaData.populate(AbstractMemberMetaData.java:489)
	at org.datanucleus.metadata.ClassMetaData.populateMemberMetaData(ClassMetaData.java:543)
	at org.datanucleus.metadata.ClassMetaData.populate(ClassMetaData.java:205)
	at org.datanucleus.metadata.MetaDataManager$1.run(MetaDataManager.java:2393)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.datanucleus.metadata.MetaDataManager.populateAbstractClassMetaData(MetaDataManager.java:2387)
	at org.datanucleus.metadata.MetaDataManager.populateFileMetaData(MetaDataManager.java:2224)
	at org.datanucleus.metadata.MetaDataManager.initialiseFileMetaDataForUse(MetaDataManager.java:924)
	at org.datanucleus.metadata.MetaDataManager.loadClasses(MetaDataManager.java:489)
	at org.datanucleus.enhancer.DataNucleusEnhancer.getFileMetadataForInput(DataNucleusEnhancer.java:791)
	at org.datanucleus.enhancer.DataNucleusEnhancer.enhance(DataNucleusEnhancer.java:582)
	at org.datanucleus.enhancer.DataNucleusEnhancer.main(DataNucleusEnhancer.java:1316)
```

**Comment by chingor13** [comment]
The class not found SEVERE warnings were also occurring in the Java 7/8 builds, but the NPE was not.

**Comment by chingor13** [comment]
Note: this also fails on Java 10
